config/routes.rb
Rails.application.routes.draw do
  root to: 'forums#index'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  resources :forums, only: :index do
    collection do
      get :secure
      get :authorized
      get :commenting
      get :commenting2
    end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/forum.rb
class Forum
  attr_accessor :timestamp, :message, :signature

  MUUT_KEY = '6E6KouiOz1'
  MUUT_SECRET = 'acP8AeMllKys7buGCpZ6PbfA'

  def initialize(user = {})
    # timestamp (in seconds). Improves security.
    @timestamp = Time.now.to_i
    # Message (base64 encoded string)
    @message = Base64.strict_encode64(user.to_json)
    # Signature (signed with private key)
    @signature = Digest::SHA1.hexdigest("#{MUUT_SECRET} #{message} #{timestamp}")
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/forums_controller.rb
class ForumsController < ApplicationController
  def index
  end

  def secure
    @forum = Forum.new
  end

  def authorized
    user = {
      user: {
        id: 'mike', # required
        displayname: 'Mike Davidson', # required
        email: 'super.mike@gmail.com',
        avatar: '//2.gravatar.com/avatar/767fc9c115a1b989744c755db47feb60',
        is_admin: true
      }
    }
    @forum = Forum.new(user)

    render template: 'forums/secure'
  end

  def commenting
    user = {
      user: {
        id: 'mike', # required
        displayname: 'Mike Davidson', # required
        email: 'super.mike@gmail.com',
        avatar: '//2.gravatar.com/avatar/767fc9c115a1b989744c755db47feb60',
        is_admin: false
      }
    }
    @forum = Forum.new(user)
  end

  def commenting2
    user = {
      user: {
        id: 'mike', # required
        displayname: 'Mike Davidson', # required
        email: 'super.mike@gmail.com',
        avatar: '//2.gravatar.com/avatar/767fc9c115a1b989744c755db47feb60',
        is_admin: false
      }
    }
    @forum = Forum.new(user)
    render template: 'forums/commenting'
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/forums_helper.rb
module ForumsHelper
end

app/views/forums/commenting.html.erb
<script src="//code.jquery.com/jquery-1.11.2.min.js"></script>
<link rel="stylesheet" href="//cdn.muut.com/1/moot.css">
<img src="http://www.mariadcampbell.com/wp-content/uploads/2016/12/HTML5_CSS_JavaScript.png">
<a class="muut" href="https://muut.com/i/presentation/comments" type="dynamic">presentation</a>
<script src="//cdn.muut.com/1/moot.min.js"></script>
<script>
  $('#my-community').muut({
    
    api: {
      // API key for "presentation"- community
      key: '<%= Forum::MUUT_KEY %>',

      // generate following on the server side (see below)
      message: '<%= @forum.message %>',
      signature: '<%= @forum.signature %>',
      timestamp: <%= @forum.timestamp %>
    }
  })
</script>

app/views/forums/index.html.erb
<a class="muut" href="https://muut.com/i/presentation">presentation</a>
<script src="//cdn.muut.com/1/moot.min.js"></script>

app/views/forums/secure.html.erb
<script src="//code.jquery.com/jquery-1.11.2.min.js"></script>
<link rel="stylesheet" href="//cdn.muut.com/1/moot.css">
<script src="//cdn.muut.com/1/moot.min.js"></script>
<a id="my-community" href="https://muut.com/i/presentation/general">Community</a>

<script>
  $('#my-community').muut({
    
    api: {
      // API key for "presentation"- community
      key: '<%= Forum::MUUT_KEY %>',

      // generate following on the server side (see below)
      message: '<%= @forum.message %>',
      signature: '<%= @forum.signature %>',
      timestamp: <%= @forum.timestamp %>
    }
  })
</script>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>MuutForum</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
  <ul>
    <li><%= link_to 'Home', root_path %></li>
    <li><%= link_to 'Secure', secure_forums_path %></li>
    <li><%= link_to 'Authorized', authorized_forums_path %></li>
    <li><%= link_to 'Comments', commenting_forums_path %></li>
  </ul>
    <%= yield %>
  </body>
</html>